const RESOURCE = {
  USER_PLUGIN_INIT_FAILED: '用户插件初始化失败',
  MENU_PLUGIN_INIT_FAILED: '菜单插件初始化失败',
  MESSAGE_PLUGIN_INIT_FAILED: '消息插件初始化失败',
  NAVIGATOR_PLUGIN_INIT_FAILED: '导航插件初始化失败',
  TOOLS_PLUGIN_INIT_FAILED: '工具插件初始化失败',
  PLUGINS_INIT_FAILED: '插件初始化失败',
  AUTHENTICATE_FAILED: '身份验证失败',
  TOKEN_NOT_FOUND: '未检测到用户凭证信息',
  CONFIG_INVALID: '未读取到正确的应用配置信息',
  BROAD_NOTIFY_FAILED: '广播通知失败',
  ERROR_MESSAGE: '系统异常',
  TOKEN_INVALID: '用户凭证错误',
  UNIQUE_PLUGIN_ERROR: '指定的应用已存在, 请先关闭该应用',
  UNSUPPORT_REQUEST_KEY: '暂不支持指定的请求类型(KEY)',
  UNSUPPORT_REQUEST_ACTION: '暂不支持指定的请求操作(ACTION)',
  INVALID_REQUEST_PAYLOAD: '检测到错误的请求数据',
  FUNCTION_REQUEST_EXCEPTION: '远程调用服务时发生异常',
  INVALID_REQUEST_PARAM_TOKEN_VERIFY: '身份认证请求中携带了错误参数',
  ELEMENT_REQUEST_NOTFOUND_MODAL_ACTIVE: '没有找到指定的激活插件',
  INVALID_REQUEST_PARAM_NAVIGATOR: '导航请求中未携带有效参数',
  INVALID_REQUEST_PARAM_PERMISSION_SEARCH: '查询用户权限请求中未携带有效参数',
  INVALID_ANNOUNCE_DATA: '公告数据异常',
  REQUEST_OPEN_ANNOUNCE_FAILED: '请求打开公告页面时发生异常',
  REQUEST_CLOSE_ANNOUNCE_FAILED: '请求关闭公告页面时发生异常',
  INVALID_REQUEST_PARAM_DIALOG_POP: '对话框请求中未携带有效参数'
};

export default RESOURCE;
